"""empty message

Revision ID: 03daf25cd481
Revises: d337cfa9899a
Create Date: 2022-10-28 22:19:05.121430

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03daf25cd481'
down_revision = 'd337cfa9899a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_active')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
