"""empty message

Revision ID: 76878e690cb4
Revises: 03daf25cd481
Create Date: 2022-11-02 20:54:24.977459

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76878e690cb4'
down_revision = '03daf25cd481'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('planet', 'population',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=250),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('planet', 'population',
               existing_type=sa.String(length=250),
               type_=sa.INTEGER(),
               existing_nullable=True)
    # ### end Alembic commands ###
